version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mysql:5.7-ram
        environment:
         - APP_DEBUG: true
         - APP_ENV: testing
         - APP_KEY: base64:jjQIfZ1t+yLVB3FT16/CSNwdcNb9CTdHCyPR/HiS5/M=
         - DB_CONNECTION: circle_test
         - MYSQL_ROOT_HOST: '%'
         - MYSQL_ALLOW_EMPTY_PASSWORD: true
         - MYSQL_DATABASE: circle_test
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit
    deploy:
          machine:
            image: circleci/classic:edge
          steps:
            - add_ssh_keys:
                fingerprints:
                  - 2f:ef:be:7a:a3:41:37:30:c2:55:52:57:1a:cc:e9:38
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/laravel-docker/src/indvshop && git pull origin 16-S3UpDownload'
    workflows:
        version: 2
        build_and_deploy:
          jobs:
            - build
            - deploy:
                requires:
                  - build
                filters:
                  branches:
                    only: 16-S3UpDownload
